name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - release-*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Go vet
        run: go vet ./...
      - name: Go test
        run: go test -v ./...
